name: CI

on:
  push:

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-test.yaml@8b15457d79a6259c272ab9c3058e80499ae408f1
    permissions:
      contents: read
